---
- hosts: all
  become: yes
  tasks:
   - name: i want install git, tree, wget on ubuntu
     apt:
      name: "{{ item}}"
      state: present
      with_items:
       - git
       - tree
       - wget